//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Category
    {
        [DisplayName("Category ID")]
        public int CategoryID { get; set; }
        [DisplayName("Category Name")]
        [Required(ErrorMessage = "Required Category Name")]
        public string CategoryName { get; set; }
        [DisplayName("Category Description")]
        public string Description { get; set; }
    }
}
